openapi: 3.0.2
info:
  contact:
    email: rlee@163.com
    name: Ryan Li
  license:
    name: MIT
    url: https://mit-license.org/
  title: 上报审批系统后台服务 API
  version: 0.9.0
servers:
  - url: http://localhost:3000/rest
  - url: http://{host}:{port}/{contextPath}
    variables:
      host:
        default: localhost
      port:
        default: "9003"
      contextPath:
        default: rest
paths:
  /application/create:
    post:
      description: 申请人在“申请页面”填写相关信息并提交申请，将调用此 API 来创建一个新申请。
      operationId: createApplication
      requestBody:
        content:
          application/json:
            examples:
              包干修复初审:
                value:
                  type: 包干修复
                  applicant: 定损员用户ID
                  applicantName: 定损员真实姓名
                  startDate: 2020-06-30T14:10:20.391
                  caseNo: PICC-123456
                  plateNo: 鄂A-12345
                  vehicleModel: 奔驰 GLC 260 豪华型
                  repairPlant: 武汉星隆汽车销售服务有限公司
                  actualCost: "250000"
                  evaluationCost: "250000"
                  purchasePrice: "422800"
                  agreementAmount: "100000"
                  investigator: 定损员A
                  investigateDate: 2020-06-28
              高价值件初审:
                value:
                  type: 高价值件
                  applicant: 定损员用户ID
                  applicantName: 定损员真实姓名
                  startDate: 2020-06-30T14:10:20.391
                  caseNo: PICC-123456
                  plateNo: 鄂A-12345
                  vehicleModel: 奔驰 GLC 260 豪华型
                  investigator: 定损员A
                  investigateLocation: 武汉星隆汽车销售服务有限公司
                  investigateDate: 2020-06-28
                  identifier: LBVNPU39008SB69093
                  insurer: 市人保营业部
                  insured: 奔驰车主
                  finalAmount: "50000"
                  deductible: "10000"
              总成部件初审:
                value:
                  type: 总成部件
                  applicant: 定损员用户ID
                  applicantName: 定损员真实姓名
                  startDate: 2020-06-30T14:10:20.391
                  caseNo: PICC-123456
                  plateNo: 鄂A-12345
                  vehicleModel: 奔驰 GLC 260 豪华型
                  investigator: 定损员A
                  investigateLocation: 武汉星隆汽车销售服务有限公司
                  investigateDate: 2020-06-28
                  identifier: LBVNPU39008SB69093
                  insurer: 市人保营业部
                  insured: 奔驰车主
                  finalAmount: "100000"
                  deductible: "20000"
              调价申请初审:
                value:
                  type: 包干修复
                  applicant: 定损员用户ID
                  applicantName: 定损员真实姓名
                  startDate: 2020-06-30T14:10:20.391
                  caseNo: PICC-123456
                  plateNo: 鄂A-12345
                  vehicleModel: 奔驰 GLC 260 豪华型
                  investigator: 定损员A
                  investigateDate: 2020-06-28
                  occurredDate: 2020-06-14
                  quoteDate: 2020-06-25
                  quoteAmount: "20000"
                  targetAmount: "25000"
            schema:
              $ref: "#/components/schemas/ApplicationDetailDto"
        required: true
      responses:
        "200":
          content:
            application/json:
              example:
                code: 20000
                data: bc8d2f78-ba94-11ea-b3de-0242ac130004
              schema:
                $ref: "#/components/schemas/ApplicationCreateResDto"
          description: OK
      summary: 创建一个申请
      tags:
        - Application
      x-eov-operation-handler: controllers/ApplicationController
  /application/update:
    post:
      description: 通过任务ID来更新一个申请的内容（流程变量）
      operationId: updateApplication
      requestBody:
        content:
          application/json:
            example:
              type: 包干修复
              applicant: 定损员用户ID
              applicantName: 定损员真实姓名
              startDate: 2020-06-30T14:10:20.391
              caseNo: PICC-123456
              plateNo: 鄂A-12345
              vehicleModel: 奔驰 GLC 260 豪华型
              repairPlant: 武汉星隆汽车销售服务有限公司
              actualCost: "250000"
              evaluationCost: "250000"
              purchasePrice: "422800"
              agreementAmount: "100000"
              investigator: 定损员A
              investigateDate: 2020-06-28
              approved: false
              approvalHistory:
                - approver: zhangyang
                  approverName: 张洋
                  approvalDate: 2020-08-03T08:12:27.976Z
                  approvalConclusion: 移交
                  approvalComment: 移交给李捷组长。
                - approver: lijie,
                  approverName: 李捷
                  approvalDate: 2020-08-03T08:13:08.442Z
                  approvalConclusion: 移交
                  approvalComment: 移交给冯明组长。
                - approver: fengming
                  approverName: 冯明
                  approvalDate: 2020-08-03T08:13:57.948Z
                  approvalConclusion: 驳回
                  approvalComment: 不同意评估底价。
            schema:
              $ref: "#/components/schemas/ApplicationDetailDto"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SimpleSuccessResDto"
          description: OK
      summary: 更新一个申请的内容
      tags:
        - Application
      x-eov-operation-handler: controllers/ApplicationController
  /application/history:
    get:
      description: 通过 Process ID 查询历史申请详情
      operationId: getHistory
      parameters:
        - description: 申请流程ID
          explode: true
          in: query
          name: id
          required: false
          schema:
            type: string
          style: form
      responses:
        "200":
          content:
            application/json:
              example:
                code: 20000
                data:
                  type: 包干修复
                  applicant: lisi
                  applicantName: 李四
                  startDate: 2020-07-28
              schema:
                $ref: "#/components/schemas/HistoryQueryResDto"
          description: OK
      summary: 查询历史申请详情
      tags:
        - Application
      x-eov-operation-handler: controllers/ApplicationController
    post:
      description: 通过用户名、用户角色、时间段来查询和用户相关的，已完成的申请详情
      operationId: getHistoryList
      requestBody:
        content:
          application/json:
            example:
              username: zhangsan
              roles:
                - 定损员
              queryStatDate: 2020-07-15
            schema:
              $ref: "#/components/schemas/HistoryListQueryDto"
        required: true
      responses:
        "200":
          content:
            application/json:
              example:
                code: 20000
                data:
                  - type: 包干修复
                    applicant: lisi
                    applicantName: 李四
                    startDate: 2020-07-28
                  - type: 包干修复
                    applicant: wangwu
                    applicantName: 王五
                    startDate: 2020-07-25
              schema:
                $ref: "#/components/schemas/HistoryListQueryResDto"
          description: OK
      summary: 查询已完成的历史申请详情
      tags:
        - Application
      x-eov-operation-handler: controllers/ApplicationController
  /task:
    get:
      description: 通过 Task ID 查询申请的详情
      operationId: getApplicationDetail
      parameters:
        - description: 任务 ID
          explode: true
          in: query
          name: id
          required: false
          schema:
            type: string
          style: form
      responses:
        "200":
          content:
            application/json:
              example:
                code: 20000
                data:
                  type: 包干修复
                  applicant: lisi
                  applicantName: 李四
                  startDate: 2020-07-28
              schema:
                $ref: "#/components/schemas/ApplicationDetailResDto"
          description: OK
      summary: 查询用户任务详情
      tags:
        - Task
      x-eov-operation-handler: controllers/TaskController
    post:
      description: 通过用户名和用户角色来查询相关的用户任务详情列表
      operationId: getTaskList
      requestBody:
        content:
          application/json:
            example:
              username: 张三
              roles:
                - 组长
                - 包干修复初审
            schema:
              $ref: "#/components/schemas/TaskListQueryDto"
        required: true
      responses:
        "200":
          content:
            application/json:
              example:
                code: 20000
                data:
                  - type: 包干修复
                    applicant: lisi
                    applicantName: 李四
                    startDate: 2020-07-28
                  - type: 包干修复
                    applicant: wangwu
                    applicantName: 王五
                    startDate: 2020-07-25
              schema:
                $ref: "#/components/schemas/TaskListQueryResDto"
          description: OK
      summary: 查询用户任务详情列表
      tags:
        - Task
      x-eov-operation-handler: controllers/TaskController
  /task/claim:
    post:
      description: |
        审批任务有时会只指定了候选组，而没有指定审批人。通过这个 API 可以指定审批人，并清空候选组。
      operationId: claimApproval
      requestBody:
        content:
          application/json:
            example:
              id: task-id
              username: zhangsan
            schema:
              $ref: "#/components/schemas/ApprovalClaimDto"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SimpleSuccessResDto"
          description: OK
      summary: 认领一个审批任务
      tags:
        - Task
      x-eov-operation-handler: controllers/TaskController
  /task/complete:
    post:
      description: |
        审批人在“审批页面”填写审批意见，并签署审批结果：
        - “同意”，申请流程将结束。 - “驳回”，要求申请人补充材料。 - “上报“（仅”组长“角色可以上报给主任），上报给主任审批。 - ”移交“（仅”组长“角色可移交给其他组长），移交给其他组长审批。
      operationId: completeApproval
      requestBody:
        content:
          application/json:
            examples:
              同意:
                value:
                  id: task-id
                  approver: zhangyang
                  approvalDate: 2020-08-01
                  approvalConclusion: 同意
                  approvalComment: 同意本次申请。
              驳回:
                value:
                  id: task-id
                  approver: zhangyang
                  approvalDate: 2020-08-01
                  approvalConclusion: 驳回
                  approvalComment: 驳回的理由。
              上报:
                value:
                  id: task-id
                  approver: zhangyang
                  approvalDate: 2020-08-01
                  approvalConclusion: 上报
                  approvalComment: 上报的理由。
                  nextApprover:
                    user: ""
                    group: 主任
              移交:
                value:
                  id: task-id
                  approver: zhangyang
                  approvalDate: 2020-08-01
                  approvalConclusion: 移交
                  approvalComment: 移交的理由。
                  nextApprover:
                    user: lijie
                    group: ""
            schema:
              $ref: "#/components/schemas/ApprovalCompleteDto"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SimpleSuccessResDto"
          description: OK
      summary: 完成一个申请的审批
      tags:
        - Task
      x-eov-operation-handler: controllers/TaskController
components:
  schemas:
    ResponseCode:
      properties:
        code:
          description: |
            `20000`: 操作成功 <br> `60204`: 不正确的用户名或密码 <br> `50008`: 无效的 token <br> `50012`: 已在其它客户端登录 <br> `50014`: 过期的 token
          type: integer
      type: object
    SimpleSuccessResDto:
      allOf:
        - $ref: "#/components/schemas/ResponseCode"
        - $ref: "#/components/schemas/SimpleSuccessResDto_allOf"
      example:
        code: 20000
        data: Success
    ApplicationDetailDto:
      example:
        agreementAmount: agreementAmount
        insured: insured
        purchasePrice: purchasePrice
        type: 包干修复
        quotedAmount: quotedAmount
        investigator: investigator
        approved: true
        approvalHistory:
          - approver: approver
            approvalDate: approvalDate
            approvalComment: approvalComment
            approvalConclusion: 同意
            approverName: approverName
          - approver: approver
            approvalDate: approvalDate
            approvalComment: approvalComment
            approvalConclusion: 同意
            approverName: approverName
        insurer: insurer
        finalAmount: finalAmount
        evaluationCost: evaluationCost
        vehicleModel: vehicleModel
        id: id
        actualCost: actualCost
        occurredDate: occurredDate
        identifier: identifier
        plateNo: plateNo
        targetAmount: targetAmount
        applicantName: applicantName
        caseNo: caseNo
        applicant: applicant
        offerDate: offerDate
        deductible: deductible
        repairPlant: repairPlant
        startDate: startDate
        investigateLocation: investigateLocation
        investigateDate: investigateDate
      properties:
        type:
          description: 审批类型。
          enum:
            - 包干修复
            - 高价值件
            - 总成部件
            - 调价申请
          type: string
        applicant:
          description: 申请人用户ID（username）。
          type: string
        applicantName:
          description: 申请人的真实姓名。
          type: string
        startDate:
          description: |
            提交申请的时间，格式为`YYYY-MM-DDTHH:mm:ss.SSSZZ`（[moment.js](http://momentjs.cn/docs/#/displaying/format/)）
          type: string
        caseNo:
          description: 报案号
          type: string
        plateNo:
          description: 车牌号
          type: string
        vehicleModel:
          description: 车辆型号
          type: string
        repairPlant:
          description: 修理厂名称
          type: string
        actualCost:
          description: 实际价值
          type: string
        evaluationCost:
          description: 评估价值
          type: string
        purchasePrice:
          description: 新车购置价
          type: string
        agreementAmount:
          description: 一次性协议定损金额
          type: string
        investigator:
          description: 定损员真实姓名（name）。
          type: string
        investigateLocation:
          description: 定损地点
          type: string
        investigateDate:
          description: |
            定损时间，，格式为`YYYY-MM-DDTHH:mm:ss.SSSZZ`（[moment.js](http://momentjs.cn/docs/#/displaying/format/)）
          type: string
        identifier:
          description: 识别代码
          type: string
        insurer:
          description: 承保公司
          type: string
        insured:
          description: 被保险人姓名
          type: string
        finalAmount:
          description: 最终价格
          type: string
        deductible:
          description: 自付标准
          type: string
        occurredDate:
          description: |
            出险时间，，格式为`YYYY-MM-DDTHH:mm:ss.SSSZZ`（[moment.js](http://momentjs.cn/docs/#/displaying/format/)）
          type: string
        offerDate:
          description: |
            报价时间，，格式为`YYYY-MM-DDTHH:mm:ss.SSSZZ`（[moment.js](http://momentjs.cn/docs/#/displaying/format/)）
          type: string
        quotedAmount:
          description: 报价金额
          type: string
        targetAmount:
          description: 目标金额
          type: string
        approved:
          description: 是否同意。`true`，同意；`false`，驳回
          type: boolean
        approvalHistory:
          items:
            $ref: "#/components/schemas/ApprovalDetailDto"
          type: array
        id:
          description: 当前任务ID
          type: string
      required:
        - applicant
        - applicantName
        - startDate
        - type
      type: object
    ApplicationCreateResDto:
      allOf:
        - $ref: "#/components/schemas/ResponseCode"
        - $ref: "#/components/schemas/ApplicationCreateResDto_allOf"
    TaskListQueryDto:
      example:
        roles:
          - roles
          - roles
        username: username
      properties:
        username:
          description: 用户名
          type: string
        roles:
          items:
            description: 用户角色
            type: string
          type: array
      type: object
    TaskListQueryResDto:
      allOf:
        - $ref: "#/components/schemas/ResponseCode"
        - $ref: "#/components/schemas/TaskListQueryResDto_allOf"
    ApplicationDetailResDto:
      allOf:
        - $ref: "#/components/schemas/ResponseCode"
        - $ref: "#/components/schemas/ApplicationDetailResDto_allOf"
    ApprovalDetailDto:
      example:
        approver: approver
        approvalDate: approvalDate
        approvalComment: approvalComment
        approvalConclusion: 同意
        approverName: approverName
      properties:
        approver:
          description: 审批人用户ID
          type: string
        approverName:
          description: 审批人真实姓名
          type: string
        approvalDate:
          description: 审批时间
          type: string
        approvalConclusion:
          description: 审批
          enum:
            - 同意
            - 驳回
            - 上报
            - 移交
          type: string
        approvalComment:
          description: 审批意见
          type: string
      required:
        - approvalConclusion
        - approvalDate
        - approver
        - approverName
      type: object
    ApprovalCompleteDto:
      allOf:
        - $ref: "#/components/schemas/ApprovalCompleteDto_allOf"
        - $ref: "#/components/schemas/ApprovalDetailDto"
    ApprovalClaimDto:
      example:
        id: id
        username: username
      properties:
        id:
          description: 审批任务ID
          type: string
        username:
          description: 审批人用户ID
          type: string
      required:
        - id
        - username
      type: object
    HistoryListQueryDto:
      example:
        queryStatDate: queryStatDate
        roles:
          - roles
          - roles
        username: username
      properties:
        username:
          description: 用户名
          type: string
        roles:
          items:
            description: 用户角色
            type: string
          type: array
        queryStatDate:
          description: 查询的起始日期
          type: string
      type: object
    HistoryListQueryResDto:
      allOf:
        - $ref: "#/components/schemas/ResponseCode"
        - $ref: "#/components/schemas/TaskListQueryResDto_allOf"
    HistoryQueryResDto:
      allOf:
        - $ref: "#/components/schemas/ResponseCode"
        - $ref: "#/components/schemas/ApplicationDetailResDto_allOf"
    SimpleSuccessResDto_allOf:
      properties:
        data:
          description: 总是 "Success"
          type: string
    ApplicationCreateResDto_allOf:
      properties:
        data:
          description: 申请流程ID
          type: string
    TaskListQueryResDto_allOf:
      properties:
        data:
          items:
            $ref: "#/components/schemas/ApplicationDetailDto"
          type: array
    ApplicationDetailResDto_allOf:
      properties:
        data:
          $ref: "#/components/schemas/ApplicationDetailDto"
    ApprovalCompleteDto_allOf_nextApprover:
      description: 指定下一个审批人
      properties:
        user:
          type: string
        group:
          type: string
    ApprovalCompleteDto_allOf:
      properties:
        id:
          description: 审批任务 ID
          type: string
        nextApprover:
          $ref: "#/components/schemas/ApprovalCompleteDto_allOf_nextApprover"
      required:
        - id
