openapi: 3.0.0
info:
  title: 上报审批系统 API
  description: 上报审批系统前后台交互 API 定义
  contact:
    name: Ryan Li
    email: rlee@163.com
  version: 0.1.0
servers:
- url: /api
paths:
  /users/login:
    post:
      tags:
      - users
      summary: 用户登录
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
              examples:
                登录成功:
                  value:
                    code: 20000
                    data:
                      token: dingsun-token
                登录失败:
                  value:
                    code: 60204
                    message: 不正确的用户名或密码
        default:
          description: 未知错误
      x-swagger-router-controller: Users
  /users/info:
    get:
      tags:
      - users
      summary: 获取用户信息
      description: |
        通过 token 获取用户信息，必须先登录成功。
      operationId: getInfo
      parameters:
      - name: token
        in: query
        description: 用户 token
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: dingsun-token
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        default:
          description: 未知错误
      x-swagger-router-controller: Users
  /users/logout:
    post:
      tags:
      - users
      summary: 用户登出
      operationId: logout
      parameters:
      - name: X-Token
        in: header
        description: 通过 `header` 中的 `X-Token` 来传递 token
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: dingsun-token
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
        default:
          description: 未知错误
      x-swagger-router-controller: Users
components:
  schemas:
    body:
      required:
      - password
      - username
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      example:
        username: dingsun
        password: "123"
    inline_response_200:
      type: object
      properties:
        code:
          type: integer
          description: |
            `20000`: 登录成功 <br> `60204`: 不正确的用户名或密码
          format: int64
        data:
          type: object
          properties:
            token:
              type: string
          example:
            token: token
        message:
          type: string
      example:
        code: 0
        data:
          token: token
        message: message
    inline_response_200_1:
      type: object
      properties:
        code:
          type: integer
          description: |
            `20000`: 获取成功 <br> `50008`: 无效的 token <br> `50012`: 已在其它客户端登录 <br> `50014`: 过期的 token
          format: int64
        data:
          type: object
          properties:
            name:
              type: string
              description: 用户的真实姓名
            avatar:
              type: string
              description: 用户头像的 url
            introduction:
              type: string
              description: 用户的详细介绍
            roles:
              type: array
              items:
                type: string
                description: 用户所属的角色列表
      example:
        code: 20000
        data:
          name: 定损员
          avatar: /avatar/memberOfLosses.png
          introduction: 定损员可以创建申请
          roles:
          - 定损员
    inline_response_200_2:
      type: object
      properties:
        code:
          type: integer
          format: int64
        data:
          type: string
      example:
        code: 20000
        data: success
