openapi: 3.0.2

info:
  title: 上报审批系统后台服务 API
  version: 0.9.0
  license:
    name: MIT
    url: https://mit-license.org/
  contact:
    name: Ryan Li
    email: rlee@163.com

servers:
  - url: http://localhost:3000/rest
  - url: http://{host}:{port}/{contextPath}
    variables:
      host:
        default: localhost
      port:
        default: "9003"
      contextPath:
        default: rest

paths:
  /application/create:
    post:
      summary: 创建一个申请
      description: 申请人在“申请页面”填写相关信息并提交申请，将调用此 API 来创建一个新申请。
      operationId: createApplication
      tags:
        - Application

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ApplicationDetailDto"
            examples:
              包干修复初审:
                value:
                  state: 初审
                  type: 包干修复
                  applicant: 定损员A
                  startDate: "2020-06-30T14:10:20.391"
                  caseNo: PICC-123456
                  plateNo: 鄂A-12345
                  vehicleModel: 奔驰 GLC 260 豪华型
                  repairPlant: 武汉星隆汽车销售服务有限公司
                  actualCost: "250000"
                  evaluationCost: "250000"
                  purchasePrice: "422800"
                  agreementAmount: "100000"
                  investigator: 定损员A
                  investigateDate: 2020-06-28
              高价值件初审:
                value:
                  state: 初审
                  type: 高价值件
                  applicant: 定损员A
                  startDate: "2020-06-30T14:10:20.391"
                  caseNo: PICC-123456
                  plateNo: 鄂A-12345
                  vehicleModel: 奔驰 GLC 260 豪华型
                  investigator: 定损员A
                  investigateLocation: 武汉星隆汽车销售服务有限公司
                  investigateDate: 2020-06-28
                  identifier: LBVNPU39008SB69093
                  insurer: 市人保营业部
                  insured: 奔驰车主
                  finalAmount: "50000"
                  deductible: "10000"
              总成部件初审:
                value:
                  state: 初审
                  type: 总成部件
                  applicant: 定损员A
                  startDate: "2020-06-30T14:10:20.391"
                  caseNo: PICC-123456
                  plateNo: 鄂A-12345
                  vehicleModel: 奔驰 GLC 260 豪华型
                  investigator: 定损员A
                  investigateLocation: 武汉星隆汽车销售服务有限公司
                  investigateDate: 2020-06-28
                  identifier: LBVNPU39008SB69093
                  insurer: 市人保营业部
                  insured: 奔驰车主
                  finalAmount: "100000"
                  deductible: "20000"
              调价申请初审:
                value:
                  state: 初审
                  type: 包干修复
                  applicant: 定损员A
                  startDate: "2020-06-30T14:10:20.391"
                  caseNo: PICC-123456
                  plateNo: 鄂A-12345
                  vehicleModel: 奔驰 GLC 260 豪华型
                  investigator: 定损员A
                  investigateDate: 2020-06-28
                  occurredDate: 2020-06-14
                  quoteDate: 2020-06-25
                  quoteAmount: "20000"
                  targetAmount: "25000"

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationCreateResDto"
              example:
                code: 20000
                data: "bc8d2f78-ba94-11ea-b3de-0242ac130004"

  /task:
    post:
      tags:
        - Task
      summary: 查询用户任务详情列表
      description: 通过用户名和用户角色来查询相关的用户任务详情列表
      operationId: getTaskList

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskListQueryDto"
            example:
              userid: 张三
              roles:
                - "组长"
                - "包干修复初审"

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskListQueryResDto"
              example:
                code: 20000
                data:
                  - state: 初审
                    type: 包干修复
                    applicant: lisi
                    startDate: 2020-07-28
                  - state: 初审
                    type: 包干修复
                    applicant: wangwu
                    startDate: 2020-07-25

    get:
      tags:
        - Task
      summary: 查询用户任务详情
      description: 通过 Task ID 查询申请的详情
      operationId: getApplicationDetail

      parameters:
        - in: query
          name: id
          schema:
            type: string
          description: 任务 ID

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationDetailResDto"
              example:
                code: 20000
                data:
                  state: 初审
                  type: 包干修复
                  applicant: lisi
                  startDate: 2020-07-28

  /task/claim:
    post:
      summary: 认领一个审批任务
      description: >
        审批任务有时会只指定了候选组，而没有指定审批人。通过这个 API 可以指定审批人，并清空候选组。
      operationId: claimApproval
      tags:
        - Task

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ApprovalClaimDto"
            example:
              id: task-id
              userid: zhangsan

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SimpleSuccessResDto"
              example:
                code: 20000
                data: Success

  /task/complete:
    post:
      summary: 完成一个申请的审批
      description: >
        审批人在“审批页面”填写审批意见，并签署审批结果：

        - “同意”，申请流程将结束。
        - “驳回”，要求申请人补充材料。
        - “上报“（仅”组长“角色可以上报给主任），上报给主任审批。
        - ”移交“（仅”组长“角色可移交给其他组长），移交给其他组长审批。
      operationId: completeApproval
      tags:
        - Task

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ApprovalCompleteDto"
            examples:
              同意:
                value:
                  id: task-id
                  approver: zhangyang
                  approvalDate: 2020-08-01
                  approvalConclusion: 同意
                  approvalComment: 同意本次申请。
              驳回:
                value:
                  id: task-id
                  approver: zhangyang
                  approvalDate: 2020-08-01
                  approvalConclusion: 驳回
                  approvalComment: 驳回的理由。
              上报:
                value:
                  id: task-id
                  approver: zhangyang
                  approvalDate: 2020-08-01
                  approvalConclusion: 上报
                  approvalComment: 上报的理由。
                  nextApprover:
                    user: ""
                    group: "主任"
              移交:
                value:
                  id: task-id
                  approver: zhangyang
                  approvalDate: 2020-08-01
                  approvalConclusion: 移交
                  approvalComment: 移交的理由。
                  nextApprover:
                    user: "lijie"
                    group: ""

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SimpleSuccessResDto"
              example:
                code: 20000
                data: Success

components:
  schemas:
    ResponseCode:
      type: object
      properties:
        code:
          type: integer
          description: >
            `20000`: 操作成功 <br>
            `60204`: 不正确的用户名或密码 <br>
            `50008`: 无效的 token <br>
            `50012`: 已在其它客户端登录 <br>
            `50014`: 过期的 token

    ApplicationDetailDto:
      required:
        - state
        - type
        - applicant
        - applicantName
        - startDate
      type: object
      properties:
        state:
          type: string
          description: 审批状态。开始申请时，状态为“初审”。
          enum: [初审, 复审]
        type:
          type: string
          description: 审批类型。
          enum: [包干修复, 高价值件, 总成部件, 调价申请]
        applicant:
          type: string
          description: 申请人用户ID（userid）。
        applicantName:
          type: string
          description: 申请人的真实姓名。
        startDate:
          type: string
          description: >
            提交申请的时间，格式为`YYYY-MM-DDTHH:mm:ss.SSSZZ`（[moment.js](http://momentjs.cn/docs/#/displaying/format/)）
        caseNo:
          type: string
          description: 报案号
        plateNo:
          type: string
          description: 车牌号
        vehicleModel:
          type: string
          description: 车辆型号
        repairPlant:
          type: string
          description: 修理厂名称
        actualCost:
          type: string
          description: 实际价值
        evaluationCost:
          type: string
          description: 评估价值
        purchasePrice:
          type: string
          description: 新车购置价
        agreementAmount:
          type: string
          description: 一次性协议定损金额
        investigator:
          type: string
          description: 定损员真实姓名（name）。
        investigateLocation:
          type: string
          description: 定损地点
        investigateDate:
          type: string
          description: >
            定损时间，，格式为`YYYY-MM-DDTHH:mm:ss.SSSZZ`（[moment.js](http://momentjs.cn/docs/#/displaying/format/)）
        identifier:
          type: string
          description: 识别代码
        insurer:
          type: string
          description: 承保公司
        insured:
          type: string
          description: 被保险人姓名
        finalAmount:
          type: string
          description: 最终价格
        deductible:
          type: string
          description: 自付标准
        occurredDate:
          type: string
          description: >
            出险时间，，格式为`YYYY-MM-DDTHH:mm:ss.SSSZZ`（[moment.js](http://momentjs.cn/docs/#/displaying/format/)）
        offerDate:
          type: string
          description: >
            报价时间，，格式为`YYYY-MM-DDTHH:mm:ss.SSSZZ`（[moment.js](http://momentjs.cn/docs/#/displaying/format/)）
        quotedAmount:
          type: string
          description: 报价金额
        targetAmount:
          type: string
          description: 目标金额

    ApplicationCreateResDto:
      allOf:
        - $ref: "#/components/schemas/ResponseCode"
        - type: object
          properties:
            data:
              type: string
              description: 申请流程ID

    TaskListQueryDto:
      type: object
      properties:
        userid:
          type: string
          description: 用户名
        roles:
          type: array
          items:
            type: string
            description: 用户角色

    TaskListQueryResDto:
      allOf:
        - $ref: "#/components/schemas/ResponseCode"
        - type: object
          properties:
            data:
              type: array
              items:
                $ref: "#/components/schemas/ApplicationDetailDto"

    ApplicationDetailResDto:
      allOf:
        - $ref: "#/components/schemas/ResponseCode"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/ApplicationDetailDto"

    ApprovalDetailDto:
      type: object
      required:
        - approver
        - approvalDate
        - approvalConclusion
      properties:
        approver:
          type: string
          description: 审批人
        approvalDate:
          type: string
          description: 审批时间
        approvalConclusion:
          type: string
          enum: ["同意", "驳回", "上报", "移交"]
          description: 审批
        approvalComment:
          type: string
          description: 审批意见

    ApprovalCompleteDto:
      allOf:
        - type: object
          required:
            - id
          properties:
            id:
              type: string
              description: 审批任务 ID
            nextApprover:
              type: object
              description: 指定下一个审批人
              properties:
                user:
                  type: string
                group:
                  type: string
        - $ref: "#/components/schemas/ApprovalDetailDto"

    ApprovalClaimDto:
      type: object
      required:
        - id
        - userid
      properties:
        id:
          type: string
          description: 审批任务ID
        userid:
          type: string
          description: 审批人用户ID

    SimpleSuccessResDto:
      allOf:
        - $ref: "#/components/schemas/ResponseCode"
        - type: object
          properties:
            data:
              type: string
              description: 总是 "Success"
    # ApprovalHistoryDto:
    #   type: object
    #   properties:
    #     approvalHistory:
    #       type: array
    #       description: 审核历史记录，按时间倒序排列。
    #       items:
    #         $ref: "#/components/schemas/ApprovalDetailsDto"
